stages:
  - build
  - deploy
services:
  - docker:dind


build_staging:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker version
    - docker build --build-arg VUE_APP_COMEDIAN_API_BASE_URL=$STAGING_COMEDIAN_API_BASE_URL --build-arg VUE_APP_SPRINT_REPORTER_API_BASE_URL=$STAGING_SPRINT_REPORTER_API_BASE_URL --build-arg VUE_APP_REPORTER_API_BASE_URL=$STAGING_REPORTER_API_BASE_URL --build-arg VUE_APP_ON_DUTY_BASE_URL=$STAGING_ON_DUTY_BASE_URL --pull -t registry.gitlab.com/team-monitoring/comedian-ui .
    - docker tag registry.gitlab.com/team-monitoring/comedian-ui registry.gitlab.com/team-monitoring/comedian-ui:staging
    - docker push registry.gitlab.com/team-monitoring/comedian-ui:staging
  only:
    - master
  allow_failure: false


build_prod:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build --build-arg VUE_APP_COMEDIAN_API_BASE_URL=$PROD_COMEDIAN_API_BASE_URL --build-arg VUE_APP_SPRINT_REPORTER_API_BASE_URL=$PROD_SPRINT_REPORTER_API_BASE_URL --build-arg VUE_APP_REPORTER_API_BASE_URL=$PROD_REPORTER_API_BASE_URL --build-arg VUE_APP_ON_DUTY_BASE_URL=$PROD_ON_DUTY_BASE_URL --pull -t registry.gitlab.com/team-monitoring/comedian-ui .
    - docker tag registry.gitlab.com/team-monitoring/comedian-ui registry.gitlab.com/team-monitoring/comedian-ui:latest
    - docker push registry.gitlab.com/team-monitoring/comedian-ui
  only:
    - master
  when: manual
  allow_failure: false


staging_deploy:
  stage: deploy
  image: halfb00t/alpine:3.7
  before_script:
    - eval "$(ssh-agent -s)"
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -r ./* gitlab@$DEPLOY_SERVER_IP:/opt/docker/comedian-ui/
    - ssh gitlab@$DEPLOY_SERVER_IP "$STAGING_DEPLOY_COMMAND"
    - ssh-agent -k
  only:
    - master
  #when:
  #  manual

prod_deploy:
  stage: deploy
  image: halfb00t/alpine:3.7
  before_script:
    - eval "$(ssh-agent -s)"
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -r docker-compose-prod.yml gitlab@$DEPLOY_SERVER_IP:/opt/docker/comedian-ui-prod/docker-compose.yml
    - ssh gitlab@$DEPLOY_SERVER_IP "$DEPLOY_COMMAND"
    - ssh-agent -k
  only:
    - master
  when: manual