stages:
  - build
  - staging_deploy
services:
  - docker:dind
  
build:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build --pull -t registry.gitlab.com/team-monitoring/comedian-ui .
    - docker tag registry.gitlab.com/team-monitoring/comedian-ui registry.gitlab.com/team-monitoring/comedian-ui:staging
    - docker push registry.gitlab.com/team-monitoring/comedian-ui
    - docker push registry.gitlab.com/team-monitoring/comedian-ui:staging
  only:
    - master
  #when:
  #  manual
  allow_failure: false


staging_deploy:
  stage: staging_deploy
  image: halfb00t/alpine:3.7
  before_script:
    - eval "$(ssh-agent -s)"
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -r ./* gitlab@$DEPLOY_SERVER_IP:/opt/docker/comedian-ui/
    - ssh gitlab@$DEPLOY_SERVER_IP "$STAGING_DEPLOY_COMMAND"
    - ssh-agent -k
  only:
    - master
  #when:
  #  manual