version: '2.2'

services:


  comedian-ui:
    container_name: comedian-ui
    image: registry.gitlab.com/team-monitoring/comedian-ui:staging
    restart: always
    environment:
      - VIRTUAL_HOST=staging.comedian.maddevs.co
      - LETSENCRYPT_HOST=staging.comedian.maddevs.co
      - LETSENCRYPT_EMAIL=fedorenko.tolik@gmail.com
    expose:
      - 80


