version: '2.2'
networks:
  comedian_comedian:
    external: true

services:


  comedian-ui:
    build:
      args:
        - VUE_APP_COMEDIAN_API_BASE_URL=https://staging.comedian.maddevs.co
        - VUE_APP_SPRINT_REPORTER_API_BASE_URL=https://staging-sprint-reporter.comedian.maddevs.co
        - VUE_APP_REPORTER_API_BASE_URL=https://staging-reporter.comedian.maddevs.co
        - VUE_APP_ON_DUTY_BASE_URL=https://staging-onduty-service.comedian.maddevs.co
    container_name: comedian-ui
    image: registry.gitlab.com/team-monitoring/comedian-ui:staging
    restart: always
    environment:
      - VIRTUAL_HOST=admin-staging.comedian.maddevs.co
      - LETSENCRYPT_HOST=admin-staging.comedian.maddevs.co
      - LETSENCRYPT_EMAIL=fedorenko.tolik@gmail.com
    expose:
      - 80
    networks: 
      - comedian_comedian


