version: '2.2'
networks:
  comedian_comedian:
    external: true

services:


  comedian-ui:
    container_name: comedian-ui-prod
    image: registry.gitlab.com/team-monitoring/comedian-ui:latest
    restart: always
    environment:
      - VIRTUAL_HOST=admin.comedian.maddevs.co
      - LETSENCRYPT_HOST=admin.comedian.maddevs.co
      - LETSENCRYPT_EMAIL=fedorenko.tolik@gmail.com
    expose:
      - 80
    networks: 
      - comedian_comedian


