version: '2.2'
networks:
  comedian_comedian:
    external: true

services:
  comedian-ui:
    image: registry.gitlab.com/team-monitoring/comedian-ui:$TAG
    restart: always
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=fedorenko.tolik@gmail.com
    expose:
      - 80
    networks: 
      - comedian_comedian


